module.exports = [
    {
        "adult": false,
        "also_known_as": [
          "George Walton Lucas Jr. ",
          "乔治·卢卡斯",
          "Джордж Лукас",
          "ジョージ・ルーカス",
          "จอร์จ ลูคัส",
          "조지 루카스",
          "جورج لوكاس"
        ],
        "biography": "George Walton Lucas Jr. (born May 14, 1944) is an American filmmaker and entrepreneur. Lucas is known for creating the Star Wars and Indiana Jones franchises and founding Lucasfilm, LucasArts and Industrial Light & Magic. He served as chairman of Lucasfilm before selling it to The Walt Disney Company in 2012.\n\nAfter graduating from the University of Southern California in 1967, Lucas co-founded American Zoetrope with filmmaker Francis Ford Coppola. Lucas wrote and directed THX 1138 (1971), based on his earlier student short Electronic Labyrinth: THX 1138 4EB, which was a critical success but a financial failure. His next work as a writer-director was the film American Graffiti (1973), inspired by his youth in early 1960s Modesto, California, and produced through the newly founded Lucasfilm. The film was critically and commercially successful, and received five Academy Award nominations including Best Picture.\n\nLucas's next film, the epic space opera Star Wars (1977), had a troubled production but was a surprise hit, becoming the highest-grossing film at the time, winning six Academy Awards and sparking a cultural phenomenon. Lucas produced and co-wrote the sequels The Empire Strikes Back (1980) and Return of the Jedi (1983). With director Steven Spielberg, he created, produced and co-wrote the Indiana Jones films Raiders of the Lost Ark (1981), Temple of Doom (1984), The Last Crusade (1989) and Kingdom of the Crystal Skull (2008). He also produced and wrote a variety of films and television series through Lucasfilm between the 1970s and the 2010s.\n\nIn 1997, Lucas rereleased the Star Wars trilogy as part of a special edition featuring several alterations; home media versions with further changes were released in 2004 and 2011. He returned to directing with a Star Wars prequel trilogy comprising The Phantom Menace (1999), Attack of the Clones (2002), and Revenge of the Sith (2005). He last collaborated on the CGI-animated television series Star Wars: The Clone Wars (2008–2014, 2020), the war film Red Tails (2012), and the CGI film Strange Magic (2015).\n\nLucas is one of history's most financially successful filmmakers and has been nominated for four Academy Awards. His films are among the 100 highest-grossing movies at the North American box office, adjusted for ticket-price inflation. Lucas is considered a significant figure of the 20th-century New Hollywood movement.\n\nDescription above from the Wikipedia article George Lucas, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1944-05-14",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 1,
        "imdb_id": "nm0000184",
        "known_for_department": "Directing",
        "name": "George Lucas",
        "place_of_birth": "Modesto, California, USA",
        "popularity": 14.881,
        "profile_path": "/WCSZzWdtPmdRxH9LUCVi2JPCSJ.jpg"
      },
      {
        "adult": false,
        "also_known_as": [
          "Mark Hamil",
          "Mark Richard Hamill",
          "Марк Хэмилл",
          "Μαρκ Χάμιλ",
          "マーク・ハミル",
          "마크 해밀",
          "Patrick Williams",
          "William M. Patrick",
          "马克哈米尔",
          "馬克哈米爾"
        ],
        "biography": "Mark Richard Hamill (born September 25, 1951) is an American actor, voice artist, producer, director, and writer. Hamill is best known for his role as Luke Skywalker in the original Star Wars trilogy and also well known for voice-acting characters such as the Joker in various animated series, animated films and video games, beginning with Batman: The Animated Series, the Skeleton king in Super Robot Monkey Team Hyperforce Go!, Fire Lord Ozai in Avatar: The Last Airbender, Master Eraqus in Kingdom Hearts: Birth by Sleep, Skips in Regular Show, and Senator Stampington on Metalocalypse.",
        "birthday": "1951-09-25",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 2,
        "imdb_id": "nm0000434",
        "known_for_department": "Acting",
        "name": "Mark Hamill",
        "place_of_birth": "Oakland, California, USA",
        "popularity": 26.426,
        "profile_path": "/2ZulC2Ccq1yv3pemusks6Zlfy2s.jpg"
      },
      {
        "adult": false,
        "also_known_as": [
          "Mark Hamil",
          "Mark Richard Hamill",
          "Марк Хэмилл",
          "Μαρκ Χάμιλ",
          "マーク・ハミル",
          "마크 해밀",
          "Patrick Williams",
          "William M. Patrick",
          "马克哈米尔",
          "馬克哈米爾"
        ],
        "biography": "Mark Richard Hamill (born September 25, 1951) is an American actor, voice artist, producer, director, and writer. Hamill is best known for his role as Luke Skywalker in the original Star Wars trilogy and also well known for voice-acting characters such as the Joker in various animated series, animated films and video games, beginning with Batman: The Animated Series, the Skeleton king in Super Robot Monkey Team Hyperforce Go!, Fire Lord Ozai in Avatar: The Last Airbender, Master Eraqus in Kingdom Hearts: Birth by Sleep, Skips in Regular Show, and Senator Stampington on Metalocalypse.",
        "birthday": "1951-09-25",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 2,
        "imdb_id": "nm0000434",
        "known_for_department": "Acting",
        "name": "Mark Hamill",
        "place_of_birth": "Oakland, California, USA",
        "popularity": 26.426,
        "profile_path": "/2ZulC2Ccq1yv3pemusks6Zlfy2s.jpg"
      }
]